# Coding the algorithms

## Linear search 

In [1]:
sorted_list = [2*x for x in range(10)]
print(sorted_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [2]:
def linear_search(list, object_to_find):
    "returns index of object or -1 if not present"
    pass

In [3]:
print(linear_search(sorted_list, 8))
# returns(4)
print(linear_search(sorted_list, 7))
# rerurns(-1)

None
None


## Binary search 

In [4]:
def binary_search(list, object_to_find):
    "returns index of object or -1 if not present"
    pass

In [5]:
print(binary_search(sorted_list, 8))
# returns(4)
print(binary_search(sorted_list, 7))
# rerurns(-1)

None
None


## Recursive binary search 

In [6]:
def recursive_binary_search(list, object_to_find):
    "returns index of object or -1 if not present"
    pass

In [7]:
print(recursive_binary_search(sorted_list, 8))
# returns(4)
print(recursive_binary_search(sorted_list, 7))
# rerurns(-1)

None
None


# Comparing performance

## measuring execution time with a time difference 

In [8]:
import time 

In [9]:
# store starting time 
begin = time.time() 
  
# program body starts 
for i in range(5): 
    print("CS rocks!") 
# program body ends 

# store end time 
end = time.time()
  
# total time taken 
print(f"Total runtime of the program is {(end - begin) * 10e3}ms") 


CS rocks!
CS rocks!
CS rocks!
CS rocks!
CS rocks!
Total runtime of the program is 24.263858795166016ms


In [10]:
def time_it(func,*args):
    # store starting time 
    begin = time.time() 
    
    # program body starts 
    func(*args)
    # program body ends 

    # store end time 
    end = time.time()
    
    # total time taken 
    print(f"Total runtime of the program is {(end - begin)*10e3}ms") 


In [11]:
def print_message(n):
    for i in range(n): 
        print("CS rocks!")

In [12]:
time_it(print_message, 5)

CS rocks!
CS rocks!
CS rocks!
CS rocks!
CS rocks!
Total runtime of the program is 5.1116943359375ms


Compare performances of linear, binary and recursive binary

In [13]:
import random

In [14]:
sorted_list = [2*x for x in range(10)]
unsorted_list  = random.sample(sorted_list, len(sorted_list))
random_element = random.choice(unsorted_list)

In [15]:
time_it(linear_search, unsorted_list, random_element)
time_it(binary_search, unsorted_list, random_element)
time_it(recursive_binary_search, unsorted_list, random_element)

Total runtime of the program is 0.01430511474609375ms
Total runtime of the program is 0.016689300537109375ms
Total runtime of the program is 0.011920928955078125ms


# Binary tree implementation

## Implementation
use a 2D array with 3 columns (left, data, right)

## Recursive binary search in binary tree 

## Pre-, in-, and post-order traversal

Why does execuion time  varies? 

# Advanced topic: Tips for optimisation 

use numpy arrays 

In [16]:
import numpy as np

1D

In [17]:
l = [x for x in range(10)]
print("list:\n", l, sep="")
arr = np.array(l)
print("array:\n", arr, sep="")

list:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array:
[0 1 2 3 4 5 6 7 8 9]


2D

In [18]:
l = [[x * y for x in range (10)] for y in range(3)]
print("list:\n", l, sep="")
arr = np.array(l)
print("array:\n", arr, sep="")
print(arr[2, 6])

list:
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]]
array:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]]
12


Using multi-processing

In [19]:
from multiprocessing import Pool

def f(x):
    return x * x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))

[1, 4, 9]
