# Coding the algorithms

## Linear search 

In [2]:
sorted_list = [2*x for x in range(10)]
print(sorted_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [3]:
def linear_search(to_search: list, object_to_find: object) -> int:
    """returns index of object or -1 if not present"""
    for i, obj in enumerate(to_search):
        if object_to_find == obj:
            return i
    return -1

In [4]:
print(linear_search(sorted_list, 8))
# returns 4
print(linear_search(sorted_list, 7))
# returns -1

4
-1


## Binary search 

In [5]:
def binary_search(to_search: list, object_to_find: object) -> int:
    """returns index of object or -1 if not present"""
    start = 0
    end = len(to_search)
    while start != end:
        mid = (end - start) // 2 + start
        if to_search[mid] == object_to_find:
            return mid
        elif to_search[mid] > object_to_find:
            end = mid
        else:
            start = mid + 1
    return -1

In [6]:
print(binary_search(sorted_list, 8))
# returns 4
print(binary_search(sorted_list, 7))
# returns -1

4
-1


## Recursive binary search 

In [7]:
def recursive_binary_search(
    to_find_in: list, to_find: object, *, my_index=0
) -> int:
    """returns index of object or -1 if not present"""
    if not to_find_in:
        return -1
    items = len(to_find_in)
    search_point = items // 2
    search_val = to_find_in[search_point]
    if search_val == to_find:
        return my_index + search_point
    elif search_val < to_find:
        return recursive_binary_search(
            to_find_in[search_point + 1:], to_find, my_index=my_index + search_point + 1
        )
    else:
        return recursive_binary_search(
            to_find_in[:search_point], to_find, my_index=my_index
        )

In [8]:
print(recursive_binary_search(sorted_list, 8))
# returns 4 
print(recursive_binary_search(sorted_list, 7))
# returns -1

4
-1


# Comparing performance

## measuring execution time with a time difference 

In [9]:
import time 

In [10]:
# store starting time 
begin = time.time() 
  
# program body starts 
for i in range(5): 
    print("CS rocks!") 
# program body ends 

# store end time 
end = time.time()
  
# total time taken 
print(f"Total runtime of the program is {(end - begin) * 10e3}ms") 


CS rocks!
CS rocks!
CS rocks!
CS rocks!
CS rocks!
Total runtime of the program is 15.592575073242188ms


In [11]:
def time_it(func, *args):
    # store starting time 
    begin = time.time() 
    
    # program body starts 
    func(*args)
    # program body ends 

    # store end time 
    end = time.time()
    
    # total time taken 
    print(f"Total runtime of the program is {(end - begin) * 10e3}ms") 


In [12]:
def print_message(n):
    for i in range(n): 
        print("CS rocks!")

In [13]:
time_it(print_message, 5)

CS rocks!
CS rocks!
CS rocks!
CS rocks!
CS rocks!
Total runtime of the program is 2.658367156982422ms


Compare performances of linear, binary and recursive binary

In [14]:
import random

In [15]:
sorted_list = [2 * x for x in range(10)]
unsorted_list  = random.sample(sorted_list, len(sorted_list))
random_element = random.choice(unsorted_list)

In [16]:
time_it(linear_search, unsorted_list, random_element)
time_it(binary_search, sorted_list, random_element)
time_it(recursive_binary_search, sorted_list, random_element)
time_it(unsorted_list.index, random_element)
time_it(sorted_list.index, random_element)

Total runtime of the program is 0.0476837158203125ms
Total runtime of the program is 0.054836273193359375ms
Total runtime of the program is 0.0667572021484375ms
Total runtime of the program is 0.016689300537109375ms
Total runtime of the program is 0.011920928955078125ms


# Binary tree implementation

## Implementation
use a 2D array with 3 columns (left, data, right)

In [17]:
# I don't want to use a 2D array, I want to use objects with __slots__ D:
bin_tree = [[None for i in range(3)] for i in range(15)]
# I have no data to put in this tree
node_5 = bin_tree[5]
node_5_val = node_5[0]
node_5_left_idx = node_5[1]
node_5_right_idx = node_5[2]

## Recursive binary search in binary tree 

In [18]:
def recursive_bst_search(tree: list[list], find: object, index: int = 0) -> bool:
    root = tree[index]
    val = root[0]
    if val == find:
        return True
    elif find < val:
        left_ptr = root[1]
        if left_ptr is None:
            return False
        return recursive_bst_search(tree, find, left_ptr)
    else:
        right_ptr = root[2]
        if right_ptr is None:
            return False
        return recursive_bst_search(tree, find, right_ptr)

## Pre-, in-, and post-order traversal

Why does execution time vary? Because different traversals require different amounts of stack space and CPU availability can be pseudo-random

# Advanced topic: Tips for optimisation 

use numpy arrays 

In [19]:
import numpy as np

1D

In [20]:
l = [x for x in range(10)]
print("list:\n", l, sep="")
arr = np.array(l)
print("array:\n", arr, sep="")

list:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array:
[0 1 2 3 4 5 6 7 8 9]


2D

In [21]:
l = [[x * y for x in range (10)] for y in range(3)]
print("list:\n", l, sep="")
arr = np.array(l)
print("array:\n", arr, sep="")
print(arr[2, 6])

list:
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]]
array:
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]]
12


Using multi-processing

In [22]:
from multiprocessing import Pool

def f(x):
    return x * x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))

[1, 4, 9]
