# List comprehension

Principle: 


The idea of a list comprehension is to make code more compact to accomplish tasks involving lists. 


In [ ]:
years_of_birth = [1990, 1991, 1990, 2000, 2012, 2020]

In [ ]:
ages = []
for year in years_of_birth: 
  ages.append(2021 - year)

This code translates the years of birth into ages, and it took us a for loop and an append statement to a new list to do that.

In [ ]:
ages = [2021 - year for year in years_of_birth]

This is a list comprehension.

It accomplishes the same thing as the first code sample - at the end, the ages variable has a list containing the ages corresponding to all the birthdates.

## Exercises

Create an identical list from the first list using list comprehension.

In [ ]:
lst1=[1,2,3,4,5]

In [ ]:
copy_of_lst1 = [i for i in lst1]

Using list comprehension, construct a list from the squares of each element in the list.

In [ ]:
lst1=[1,2,3,4,5]
squared_list = [i**2 for i in lst1]

Create a list from the elements of a range from 1200 to 2000 with steps of 130, using list comprehension and the function __range()__

In [157]:
print([n for n in range(10)]) # the end value is not included! 
print([n for n in range(0,10,1)]) # start value = 0 and step = 1 (same as default) 
print([n for n in range(4,10)]) # changing start value
print([n for n in range(4,10, 2)]) # changing step
print([n for n in range(10,4, -1)]) # changing order and decreasing step

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7, 8, 9]
[4, 6, 8]
[10, 9, 8, 7, 6, 5]


In [ ]:
print([n for n in range(1200,2001,130)])

# Conditions

In [8]:
years_of_birth = [1990, 1991, 2008, 2005, 2012, 2020]
ages_of_teens = []
for year in years_of_birth:
    age = 2021 - year
    if 13<=age <= 19 : 
        ages_of_teens.append(age)

In [ ]:
ages_of_teens = [age for year in years_of_birth if 13 <= (age:=2021 - year) <= 19]

In [9]:
ages_of_teens

[13, 16]

Using list comprehension, construct a list from the squares of each element in the list, if the square is greater than 50.

In [ ]:
lst1=[2, 4, 6, 8, 10, 12, 14]
squares_above_fifty=[square for i in lst1 if (square:=i**2) > 50]


Return only the odd elements of the list

In [ ]:
lst1=[2, 5, 6, 9, 11, 12, 14]
odd_elements=[i for i in lst1 if i % 2]

## Very difficult optional question

Find all prime numbers smaller than N using a single line with list comprehension

In [2]:
n = 20
primes = [i for i in range(1,n+1) if all([i%k!=0 for k in range(2,int(i**(1/2)) + 1)])]

[1, 2, 3, 5, 7, 11, 13, 17, 19]

# Nested lists

 
to create 2D arrays 

In [108]:
rows = 3
columns = 5
arr = [[(j+1)*(i+1) for j in range(columns)] for i in range(rows)]
print(arr)
print(arr[2])
print(arr[2][4])

[[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15]]
[3, 6, 9, 12, 15]
15


### Tip: numpy library

Use numpy to manipulate these arrays easily. Numpy, being written in C, is much more efficient than python for heavy calculation.

In [142]:
import numpy as np

In [150]:
np_arr = np.array(arr)
print(np_arr) # better display of array
print(np_arr[2,4]) # accessing the elements with one set of []
print(np_arr[:,4]) # Using an empty slice takes all the rows, hence a column
print(np_arr[::-1,4]) # print the columns in reverse!! 
print(np_arr*-1.5) # multiply the whole array by a float

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]
15
[ 5 10 15]
[15 10  5]
[[ -1.5  -3.   -4.5  -6.   -7.5]
 [ -3.   -6.   -9.  -12.  -15. ]
 [ -4.5  -9.  -13.5 -18.  -22.5]]


# PACKING AND UNPACKING 
# Unpacking variables 

When we have a list, we can assign the values of the list to several variables

In [17]:
i,j,k = [1,2,3]
print(f"{i=}, {j=}, {k=}")

i=1 , j=2 , k=3


When we have a list of list, we can either use each element

In [12]:
L = [[1,'a'],[2,'b'],[3,'c']]

In [13]:
for a in L : 
    print(a) # each element is a list (i.e. "packed")

[1, 'a']
[2, 'b']
[3, 'c']


In [99]:
for a in L : 
    n,char  = a # we "unpack" each element 
    print(f"number: {n}, letter: {char}")

number : 1 , letter : a
number : 2 , letter : b
number : 3 , letter : c


or we can "unpack" the elements in the "for" loop

In [14]:
for n,char in L : # we "unpack" in the for loop
    print(f"number: {n}, letter: {char}")

number : 1 , letter a
number : 2 , letter b
number : 3 , letter c


# Packing variables with useful list functions 

## `enumerate`

This function yields tuples with the index of the element and the value of the element

In [23]:
l=["a", "b", "c"]
for n in enumerate(l) : # we do not "unpack" the tuple
    print(n)

(0, 'a')
(1, 'b')
(2, 'c')


In [29]:
l=["a", "b", "c"]
for index, element in enumerate(l) : # "unpacking" the tuple 
    print(f"index : {index} , element : {element}")

index : 0 , element : a
index : 1 , element : b
index : 2 , element : c


## Exercise 


enhance the following linear search algorithm using "enumerate"

In [ ]:
def linear_search(list_to_search, object_to_find):
    "returns index of object or -1 if not present"
    for n, obj in enumerate(list_to_search) : 
        if obj == object_to_find:
            return n
    return -1

## Function "zip"

Packing two lists together (like a zip in a garment)

In [113]:
letters = "hello"
numbers = range(5)
print([(l,n) for l,n in zip(letters, numbers)])

[('h', 0), ('e', 1), ('l', 2), ('l', 3), ('o', 4)]


## exercise 

here is a list of cars and a list of masses

print a statement like "the Sedan has a mass of 1500 kg" for each car. 

In [125]:
names = ['Sedan', 'SUV', 'Pickup', 'Minivan', 'Van', 'Semi', 'Bicycle', 'Motorcycle']
values = [1500, 2000, 2500, 1600, 2400, 13600, 7, 110]

In [ ]:
for name, mass in zip(names, values):
    print(f'The {name} has a mass of {mass}kg')

# Dictionary comprehension

you can use dict comprehension as list comprehension, providing both a UNIQUE key and a value for each key

In [126]:
dicto = {k:v for k,v in zip(names, values)}
print(dicto)

{'Sedan': 1500, 'SUV': 2000, 'Pickup': 2500, 'Minivan': 1600, 'Van': 2400, 'Semi': 13600, 'Bicycle': 7, 'Motorcycle': 110}


This equivalent to declaring the folowing dict

In [ ]:
vehicle_masses={"Sedan": 1500, "SUV": 2000, "Pickup": 2500, "Minivan": 1600, "Van": 2400, "Semi": 13600, "Bicycle": 7, "Motorcycle": 110}

when you have a dictionnary you can acess its keys or values using dict.keys or dict.values but they are __NOT__ in order*

*(except that Python gives them an order but... don't get used to such coding gifts)

In [123]:
print([k for k in vehicle_masses.keys()]) 
print([v for v in vehicle_masses.values()])

['Sedan', 'SUV', 'Pickup', 'Minivan', 'Van', 'Semi', 'Bicycle', 'Motorcycle']
[1500, 2000, 2500, 1600, 2400, 13600, 7, 110]


Much more useful is to get pairs with key AND value with dict.items() and print them as such

In [133]:
[f"The {k} has a mass of {v}kg" for k,v in vehicle_masses.items()]

['The Sedan weights 1500 kg',
 'The SUV weights 2000 kg',
 'The Pickup weights 2500 kg',
 'The Minivan weights 1600 kg',
 'The Van weights 2400 kg',
 'The Semi weights 13600 kg',
 'The Bicycle weights 7 kg',
 'The Motorcycle weights 110 kg']

## Exercise : 
Contruct a list of the names of vehicles with weight below 5000 kilograms. In the same list comprehension make the key names all upper case (str.upper).

In [137]:
"abc".upper() #here is how to force uppercase

'ABC'

In [ ]:
below_5k = [vehicle for vehicle, mass in vehicle_masses if mass < 5000]